spring:
  application:
    name: card-management-system

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "MY_SUPER_SECRET_KEY_FOR_JWT_SIGNING_1234567890_MIN_32_CHARS"

admin:
  registration-key: "MY_SUPER_SECRET_ADMIN_PASSWORD_777"

#  server:
#    port: 8081

